version: "3.8" # версия вашего docker-compose
services: # имеджи, которые запустятся по вашему желанию
  db: # название моего имеджа
    container_name: HistoricalPublication
    image: postgres:16 # скачает image postgres 16 версии
    volumes: # часть настроек для хранения данных, пока для нас это не важно
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    ports: # порты
      - "5432:5432"
    environment: # переменные окружения, меняйте их если хотите поменять пароль, логин или название стартовой базы данных
      POSTGRES_USER: postgres
      POSTGRES_DB: HistoricalPublication
      POSTGRES_PASSWORD: postgres

  minio:
    container_name: s3Minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: rip
      MINIO_SECRET_KEY: 12345678
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - minio-data:/data
      - ./migrations/minio:/migration
    command: minio server /data --console-address ":9001"
    networks:
      - minio-network

  minio-client:
    container_name: s3MinioClient
    image: minio/mc:latest
    entrypoint: >
      sh -c "until mc alias set myminio http://minio:9000 rip 12345678; do sleep 1; done && \
      mc mb myminio/events && \
      mc policy set public myminio/events && \
      mc cp /migration/events/* myminio/events/"
    depends_on:
      - minio
    volumes:
      - ./migrations/minio:/migration
    networks:
      - minio-network

volumes: # часть настроек для хранения данных
  postgresdb-data:
    driver: local
  minio-data:
    driver: local

networks:
  minio-network:
    driver: bridge
